### ISSUE TITLE
Wrong QR code for BAN deposit after switching blockchain

### ISSUE THREAD

**Issue by twister65** [wBanano/wban-dApp#110] opened 2022-12-13 03:03 UTC
If I change the Polygon blockchain to Arbitrum, the QR code for the BAN deposit on Arbitrum matches the Polygon address instead of the Arbitrum address.

**Comment by wrap-that-potassium** [comment] 2023-08-17 19:05
Duplicate of #103

**Closed by wrap-that-potassium** 2023-08-17 19:05 UTC
Labels: bug
